<<<<<<< HEAD
theme: jekyll-theme-cayman
title: RewinedDocs
description: [De plek voor onze documentatie!]




RepoName: RewinedDocs
SiteTitle: RewinedDocs

github:
  is_project_page: false

plugins:
  - jekyll-seo-tag
=======
theme: jekyll-theme-cayman
>>>>>>> d52abf5333b1f9f00fb3ae4acd917c99b7454b34
